config/routes.rb
Rails.application.routes.draw do

  resources :kittens
  root 'kittens#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
    before_action :set_kitten, only: [:show, :edit, :update, :destroy]

    def index
        @kittens = Kitten.all

        respond_to do |format|
            format.html
            format.json {render :json => @kittens}
        end
    end

    def show
        @kitten = Kitten.find(params[:id])
        respond_to do |format|
            format.html
            format.json {render :json => @kittens}
        end
    end

    def new
        @kitten = Kitten.new
    end

    def edit

    end

    def create
        @kitten = Kitten.new(kitten_params)
        respond_to do |format|
            if @kitten.save

                format.html { redirect_to @kitten, notice: "Kitten saved"}
                format.json { render :show, status: :created, location: @kitten}
                
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @kitten.errors, status: :unprocessable_entity}
            end
        end
            
    end

    def update
        respond_to do |format|
            if @kitten.update(kitten_params)
                format.html { redirect_to @kitten, notice: "Kitten updated"}
                format.json { render :show, status: :created, location: @kitten}
                
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @kitten.errors, status: :unprocessable_entity}
            end
        end
            
    end

    def destroy
        @kitten.destroy 
        respond_to do |format|
            
            format.html { redirect_to kittens_path, notice: "Kitten destroyed successfully"}
            format.json { head :no_content}
        end
    end

    private
    
    def set_kitten
        @kitten = Kitten.find(params[:id])
    end

    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kittens/_form.html.erb
<main>
    <%= form_with model: @kitten do |f|%>
        <% if kitten.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>
        <ul>
        <% kitten.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>

        <div class="row">
            <div class="column small-12">
                <%= f.text_field :name, require: true, placeholder: "Name" %>
            </div>
            <div class="column small-12">
                <%= f.text_field :age, require: true, placeholder: "Age" %>
            </div>
            <div class="column small-12">
                <%= f.text_field :cuteness, require: true, placeholder: "Cuteness" %>
            </div>
            <div class="column small-12">
            <%= f.text_field :softness, require: true, placeholder: "Softness" %>
            </div>
            <div class="column small-12">
            <%= f.submit %>
            </div>
        </div>
    
    <% end %>
</main>

app/views/kittens/edit.html.erb
<div class="row">
    <div class="column small-12">
        <%= render "form", kitten: @kitten%>

        <%= link_to "Show", kitten_path%>|
        <%= link_to "Back", kittens_path%>
    </div>
</div>

app/views/kittens/index.html.erb
<p><%= notice %></p>
<main class="clearfix">
    <div class="row limited">
        <div class="column small-12">
            <h1>Kittens</h1>
        </div>
    </div>
    
    <div class="row limited">
        <% @kittens.each do |kitten| %>
        <div class="column small-12 medium-6 large-3">
            <span id="kitten"><%= kitten.name %></span> <br />
            <span class="desc">Age: </span><%= kitten.age %> <br />
            <span class="desc">Cuteness:</span> <%=  kitten.cuteness %> <br />
            <span class="desc">Softness: </span><%= kitten.softness %> <br />
            
            <%= link_to "Show", kitten_path(kitten) %> | 
            <%= link_to "Edit", edit_kitten_path(kitten) %> | 
            
            <%= link_to "Delete", kitten, method: :delete, data: {confirmation: "Ar you sure about this?"} %>
        </div>
         <% end %>
    </div>
    <div class="row limited">
        <div class="column small-12">
           <%= link_to "New Kitten", new_kitten_path, class: "button" %> 
        </div>
    </div>
     
</main>

app/views/kittens/new.html.erb
<main>
    <div class="row limited">
        <div class="column small-12">
        <h1>Create New Kitten</h1>
        </div>
    </div>
    <div class="row limited">
        <div class="column small-12">

            <%= render "form", kitten: @kitten%>
        </div>
    </div>
    <div class="row limited">
        <div class="column small-12">
         <%= link_to "Cancel", kittens_path %> 
        </div>
    </div>
   
</main>

app/views/kittens/show.html.erb
<div class="row limited">
    <div class="column small-12">
        <p>Name: <%= @kitten.name %></p>
        <p>Age: <%= @kitten.age %></p>
        <p>Cuteness: <%= @kitten.cuteness %></p>
        <p>Softness: <%= @kitten.softness %></p>
        <%= link_to "Edit", edit_kitten_path %>|
        <%= link_to "Back", kittens_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="row limited">
        <div class="column small-12" >
          <%= image_tag("img/kitten.jpg", class: "img-responsive") %>
          <h1>Odin</h1>
          <h2>Kittens<h2>
        </div>
      </div><!-- end of row -->
    </header>
    <%= yield %>
    <footer>
      <div class="row limited">
        <div class="column small-12 medium-6 large-3">
          <h2>Partners</h2>
          <ul>
            <li><a href="#">The Odin Project</a></li>
            <li><a href="#">Google</a></li>
            <li><a href="#">Stackoverflow</a></li>
            <li><a href="#">Andala</a></li>
          </ul>
        </div>
        <div class="column small-12 medium-6 large-3">
          <h2>Quick links</h2>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Gallery</a></li>
          </ul>
        </div>
        <div class="column small-12 medium-6 large-3">
          <h2>Social</h2>
          <ul>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Instagram</a></li>
            <li><a href="#">Whatshapp</a></li>
            <li><a href="#">Twitter</a></li>
          </ul>
        </div>

        <div class="column small-12 medium-6 large-3">
          <h2>About</h2>
          <%= image_tag("img/kitten.jpg", class: "img-responsive") %>
            <p>&copy; 2021 &bull; all rights reserved.</p>
        </div>
      </div><!-- end of row-->
    </footer>

  </body>
</html>